# iterating in python 


In [5]:
import numpy as np
#1 simple iteration 
np1=np.arange(2,8)
for i in np.nditer(np1):
    print(i)
print("\r")

#2 2d array iter
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for value in np.nditer (np2):
    print(value)
print("\r")

#3 order of array using transpose
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
np3=np2.T
for i in np.nditer(np3):
    print(i)


2
3
4
5
6
7

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10


In [54]:
# style c-rows and f-colums 
#1
a=np.arange(0,60,5).reshape(3,4)
b=a.copy(order='C')
for i in np.nditer(b):
    print(i)

#2
a=np.arange(0,60,5).reshape(3,4)
b=a.copy(order='F')
for i in np.nditer(b):
    print(i)
#3    
a=np.arange(0,60,5).reshape(3,4)
for i in np.nditer(a,order='C'):
    print(i)
    

0
5
10
15
20
25
30
35
40
45
50
55
0
20
40
5
25
45
10
30
50
15
35
55
0
5
10
15
20
25
30
35
40
45
50
55


# flags in iteratror
- c_index
- f_index
- multi_index
- external_loop

In [62]:
#external_loop used to write the values into one dimension instead of 0D
a=np.arange(0,60,5).reshape(3,4)
for x in np.nditer(a,flags=['external_loop'],order='F'):
    print(x)



[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [22]:
# 
a=np.arange(0,60,5).reshape(3,4)
b=np.array([1,2,3,4],dtype='int')
for x,y in np.nditer([a,b]):
    s='{}:{}'.format(x,y)
    print(s)


0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


my name is ashish
