# Numpy where Clause
- this is used to return the index position of the element
- it is also used for if else condition type 


In [1]:
import numpy as np

In [6]:
# example 1
marks=np.array([12,33,44,56,77,89,45])
lis=np.where(marks>50)
print(lis)

(array([3, 4, 5], dtype=int64),)


In [9]:
# example 2 where is used for ifelse condition
marks=np.array([12,33,44,56,77,89,45])
np.where(marks<50,0,marks)

array([ 0,  0,  0, 56, 77, 89,  0])

# Some other function 
> it will give also the index when the certain condition is meet
- argmin()
- argmax()
- argsort()
- intersect()
  * it will work for 2D array also

In [18]:
# arg functions give the index of the values
marks=np.array([12,33,44,56,77,89,45])
marks.argmax()
marks.argmin()
marks.argsort()

array([0, 1, 2, 6, 3, 4, 5], dtype=int64)

In [17]:
# intersect 
marks=np.array([[12,33,44,56,77,89,45],[2,3,4,5,6,7,89]])
marks1=np.array([[12,33,44,57,78,89,45],[3,4,55,77,44,23,45]])
np.intersect1d(marks,marks1)


array([ 3,  4, 12, 33, 44, 45, 77, 89])