# Numpy practice 101 exercise
## level 1

1.import the numpy


In [1]:
#1--------------import the numpy---------------#
import numpy as np

In [109]:
#2------------How to create a 1D array?------------#
ar1=np.arange(0,10)
print(ar1)

[0 1 2 3 4 5 6 7 8 9]


In [110]:
#3--------------How to create a boolean array?--------------# - X
np.full((3,3),True,dtype='bool')


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
#4------------ How to extract items that satisfy a given condition from 1D array?------------------#
#-------------Extract all odd numbers from arr----------------------#
ar2=np.arange(0,10,dtype='int')
#1
res=ar2[ar2 %2 !=0]
print(res)

#2 by loop
odd_num=[]
for num in ar2:
    if num %2 != 0:
        odd_num.append(num)
print(odd_num)

#3 Solution
arr[arr % 2 == 1]


[1 3 5 7 9]
[1, 3, 5, 7, 9]


In [24]:
#5------------------- Replace all odd numbers in arr with -1----------------------#
ar3=np.arange(0,10,dtype='int')
ar3[ar3%2!=0]=-1
print(ar3)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [31]:
#6-----------------Replace all odd numbers in arr with -1 without changing arr-------------------#
#1-
ar4=np.arange(0,10,dtype='int')
ar5=ar4.copy()
ar5[ar5%2!=0]=-1
print(ar5)
print(ar4)

#2-
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [34]:
#7-----------------------Convert a 1D array to a 2D array with 2 rows----------------#
arr = np.arange(10)
res=arr.reshape(2,5)
print(res)

#2 to define the automatic coloumn use 
res1=arr.reshape(2,-1)
print(res1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [39]:
#8---------------------Stack arrays a and b vertically----------------------#
#1 using vstack
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
res=np.vstack((a,b))
print(res)

#2 using concatenate
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
res=np.concatenate((a,b),axis=0)
print(res)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
#9----------------Stack arrays a and b horizontally---------------------#
#1 using vstack
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
res=np.hstack((a,b))
print(res)

#2 using concatenate
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
res=np.concatenate((a,b),axis=1)
print(res)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [56]:
#10------------------Create the following pattern without hardcoding. Use only numpy functions and the below input array a.----------------#
a = np.array([1,2,3])
# np.r_ is used to do the multiple function use inside one 
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [59]:
#11--------------------------Get the common items between a and b----------------#

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
res=np.intersect1d(a,b)
print(res)

[2 4]


In [60]:
#12----------------------remove the same elements in array--------------#
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
res=np.setdiff1d(a,b)
print(res)

[1 2 3 4]


In [62]:
#13-------------------Get the positions where elements of a and b match-------------------#
a = np.array([1,6,3,8,5])
b = np.array([5,6,7,8,9])
res=np.where(a==b)
print(res)

(array([1, 3], dtype=int64),)


In [70]:
#14----------------extract element from a given range-----------------------#
a = np.array([2, 6, 1, 9, 10, 3, 27])
res= np.where((a>5) &( a<=10))
a[res]

array([ 6,  9, 10])

In [72]:
#16----------------swap coloumns of array------------------#
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [76]:
#17----------------swap rows of array------------------#
arr = np.arange(9).reshape(3,3)
arr
arr[[1,0,2],]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [81]:
#18---------------how to reverse the 2d array-----------#
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [82]:
#19---------------how to reverse the 2d array-----------#
arr=np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [99]:
#20-----------2d array containing random flot---------------#
np.random.randint(0,10,size=(5,3))+np.random.random((5,3))


array([[8.75337856, 6.65829436, 0.23744792],
       [1.07668886, 1.50863624, 9.71201995],
       [1.34539904, 6.92847052, 1.98909499],
       [4.03872113, 5.46973363, 0.4077788 ],
       [1.00192217, 8.72065041, 5.01444429]])

In [119]:
#21-----------print upto three decimal places---------------#
sam=np.random.random((5,3))
np.set_printoptions(precision=3) 
sam[:4]

array([[0.62 , 0.229, 0.41 ],
       [0.422, 0.258, 0.345],
       [0.807, 0.833, 0.791],
       [0.921, 0.377, 0.949]])

In [4]:
#22----------------preety print of the numpy arry-------------#
np.set_printoptions(suppress=True)
np.random.seed(100)
rand_arr=np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True,precision=6)
rand_arr

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [139]:
#23---------------Limit the number of items printed in python numpy array a to a maximum of 6 elements.---------------------#
ar1=np.arange(20)
np.set_printoptions(threshold=8,edgeitems=3)
print(ar1)

[ 0  1  2 ... 17 18 19]


In [111]:
#24--------------load the text file---------------#
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url,delimiter=',',dtype='object') # if we use none it will return 1D array 
print(iris)
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [112]:
#26----------------extract the coloumn 1d------------------#
iris=np.genfromtxt(url,delimiter=",",dtype=None)
print(iris.shape)
print(iris)
specie=np.array([row[:] for row in iris])


(150,)
[(5.1, 3.5, 1.4, 0.2, b'Iris-setosa') (4.9, 3. , 1.4, 0.2, b'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, b'Iris-setosa') (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, b'Iris-setosa') (5.4, 3.9, 1.7, 0.4, b'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, b'Iris-setosa') (5. , 3.4, 1.5, 0.2, b'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, b'Iris-setosa') (4.9, 3.1, 1.5, 0.1, b'Iris-setosa')
 (5.4, 3.7, 1.5, 0.2, b'Iris-setosa') (4.8, 3.4, 1.6, 0.2, b'Iris-setosa')
 (4.8, 3. , 1.4, 0.1, b'Iris-setosa') (4.3, 3. , 1.1, 0.1, b'Iris-setosa')
 (5.8, 4. , 1.2, 0.2, b'Iris-setosa') (5.7, 4.4, 1.5, 0.4, b'Iris-setosa')
 (5.4, 3.9, 1.3, 0.4, b'Iris-setosa') (5.1, 3.5, 1.4, 0.3, b'Iris-setosa')
 (5.7, 3.8, 1.7, 0.3, b'Iris-setosa') (5.1, 3.8, 1.5, 0.3, b'Iris-setosa')
 (5.4, 3.4, 1.7, 0.2, b'Iris-setosa') (5.1, 3.7, 1.5, 0.4, b'Iris-setosa')
 (4.6, 3.6, 1. , 0.2, b'Iris-setosa') (5.1, 3.3, 1.7, 0.5, b'Iris-setosa')
 (4.8, 3.4, 1.9, 0.2, b'Iris-setosa') (5. , 3. , 1.6, 0.2, b'Iris-setosa')
 (5. , 3.4, 1.6, 0

C:\Users\ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


IndexError: too many indices for array

In [113]:
#27----------------Convert the 1D iris to 2D array iris_2d by omitting the species text field----------------------#
#sol1
iris_1d=np.genfromtxt(url,delimiter=",",dtype=None)
iris_2d=np.array([row.tolist()[:4] for row in iris_1d])
iris_2d.shape

#2 sol2 import from the source url 
iris_2dd=np.genfromtxt(url,delimiter=",",usecols=[0,1,2,3],dtype='float')
iris_2dd[:4]

C:\Users\ashish\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [114]:
#28---------------- Find the mean, median, standard deviation of iris's sepallength (1st column)------------------#
sepallength=iris_2dd[:,:1]
me,md,std=np.mean(sepallength),np.median(sepallength),np.std(sepallength)
print(me,md,std)

5.843333333333334 5.8 0.8253012917851409


In [133]:
#29---------------Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.-----------------#

#my method
sepallength=iris_2dd[:,:1]
nor=[]
for i in sepallength:
    if i>6:
        i=1
        nor.append(i)
    else:
        i=0
        nor.append(i)
print(nor)
sepallength.tolist()
sepallength.T

#sol
Smax,Smin=sepallength.max(),sepallength.min()
nor=(sepallength-Smin)/(Smax-Smin)
np.set_printoptions(precision=2)
nor

# or use ptp()
n= (sepallength-Smin)/sepallength.ptp()
print(nor)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0]
[[0.22]
 [0.17]
 [0.11]
 [0.08]
 [0.19]
 [0.31]
 [0.08]
 [0.19]
 [0.03]
 [0.17]
 [0.31]
 [0.14]
 [0.14]
 [0.  ]
 [0.42]
 [0.39]
 [0.31]
 [0.22]
 [0.39]
 [0.22]
 [0.31]
 [0.22]
 [0.08]
 [0.22]
 [0.14]
 [0.19]
 [0.19]
 [0.25]
 [0.25]
 [0.11]
 [0.14]
 [0.31]
 [0.25]
 [0.33]
 [0.17]
 [0.19]
 [0.33]
 [0.17]
 [0.03]
 [0.22]
 [0.19]
 [0.06]
 [0.03]
 [0.19]
 [0.22]
 [0.14]
 [0.22]
 [0.08]
 [0.28]
 [0.19]
 [0.75]
 [0.58]
 [0.72]
 [0.33]
 [0.61]
 [0.39]
 [0.56]
 [0.17]
 [0.64]
 [0.25]
 [0.19]
 [0.44]
 [0.47]
 [0.5 ]
 [0.36]
 [0.67]
 [0.36]
 [0.42]
 [0.5

In [135]:
#31---------------Find the 5th and 95th percentile of iris's sepallength-------------------#
np.percentile(sepallength,q=[5,95])

array([4.6 , 7.25])

In [146]:
#32---------------Insert np.nan values at 20 random positions in iris_2d dataset---------------#
i,j=np.where(iris_2d) # where i and j denotes rows and coloumns 
np.random.seed(100)
iris_2d[np.random.choice((i),20),np.random.choice((j),20)]=np.nan
print(iris_2d[:23])
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


[[5.1 3.5 1.4 0.2]
 [nan nan nan nan]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [nan nan nan nan]
 [nan nan nan nan]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [nan nan nan nan]
 [5.4 3.4 1.7 0.2]
 [nan nan nan nan]
 [4.6 3.6 1.  0.2]]


In [152]:
#33--------------finding the missing value---------------------#
print(np.isnan(iris_2d[:,0].sum()))
print(np.where(np.isnan(iris_2d[:,0])))

(array([  1,  12,  13,  14,  19,  21,  23,  33,  34,  35,  57,  70,  79,
        87,  96, 103, 107, 126, 130, 131, 142, 144], dtype=int64),)


In [163]:
condition=(iris_2dd[:,2]>1.5) & (iris_2dd[:,0]<5.0)
print(iris_2dd[condition])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [7]:
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
a[[0,2]]=a[[2,0]]
print(a)

[[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]
