### Broadcasting rule

In [1]:
import numpy as np
np1=np.array([0,1,2,3,4,4,5,6,7])
np1[[2,3]]=33
print(np1)

[ 0  1 33 33  4  4  5  6  7]


In [4]:
### points to note while broadcasting
br_np1=np1[0:4]
print(br_np1)

#update cutoff value 
br_np1[:]=77
print(br_np1)
print(np1)



[77 77 77 77]
[77 77 77 77]
[77 77 77 77  4  4  5  6  7]


In [11]:
# how to fix this 
np1=np.arange(0,7)
br_np1=np1.copy()

br_np1[0:4]=44

print(br_np1)
print(np1)

[44 44 44 44  4  5  6]
[0 1 2 3 4 5 6]
