# Indexing of the two dimensional array

# The three metthods of indexing


## Slicing

In [3]:
                                                                                    
import numpy as np
np1=np.arange(100,130)
print (np1)
np2=np1.reshape(6,5)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129]


#### array[row_index_start : row_index_end : stepsize , col_index_start : col_index_end : step]

In [3]:
np2

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129]])

In [5]:
#indexing by row

#1 simple index
simple=np2[1][3]
print(simple)

#2 index by comma
si2=np2[2,4]
print(si2)

# index by slice
si3=np2[0:4:2,2] # to get only coloum as 1D array
print(si3)

# index by slice
np2[0:4:2,2:4] # to get only coloum as 1D array


108
114
[102 112]


array([[102, 103],
       [112, 113]])

In [7]:
#indexing by coloumn 
s=np2[5]
print(s)

# index by slice
p=np2[:,(2,4,1)]
print(p)
# index by slice 
np2[:,2:3]

[125 126 127 128 129]
[[102 104 101]
 [107 109 106]
 [112 114 111]
 [117 119 116]
 [122 124 121]
 [127 129 126]]


array([[102],
       [107],
       [112],
       [117],
       [122],
       [127]])

# indexing by index


In [112]:
#indexing using index with row and coloumn map

np3=np.arange(1,25)
print(np3)
len(np3)
ass=np3.reshape(6,4)
print(ass)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [110]:
ass[[0,2,3,4], [3, 2, 1, 0]]


array([ 4, 11, 14, 17])

# Using boolean condition for indexing 

In [120]:
np4=np.arange(0,20)
np4.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [135]:
# boleaan condtion
bool_np=np4>5
print(bool_np)

[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


In [125]:
#1
new_1=np4[(np4>4) & (np4<18)]
print(new_1)

#2 
new_2=np4[(np4%2==0)&(np4<16)]
print(new_2)



[ 5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  2  4  6  8 10 12 14]


In [132]:
# example of alternative coloumns

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [4]:
# combination of basic and advance indexing
a = np.array([[0 ,1 ,2],[3 ,4 ,5 ],
              [6 ,7 ,8],[9 ,10 ,11]])
print(a) 
print(a[1:2 ,1:3 ])
#print(a[1:2 ,[1,2]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4 5]]


In [5]:
print(a[1:2 ,[1,2]])

[[4 5]]
