# Numpy

In [1]:
import numpy as np

In [2]:
# creating a 1D array
np_1= np.array([1,2,3,4])
print(np_1)

# creating a 2d array 
np_2= np.array([[2,3,4],[3,4,5]])
print(np_2)



[1 2 3 4]
[[2 3 4]
 [3 4 5]]


In [6]:
#difference between list and array
distance=[10,22,23,23,23]
time=[5,3,2,5,6]
dis_arr=np.array(distance)
dis_ti=np.array(time)
speed= dis_arr/dis_ti
print(speed)
type(speed)
sum(dis_arr)
dis_arr* dis_ti


[ 2.          7.33333333 11.5         4.6         3.83333333]


array([ 50,  66,  46, 115, 138])

In [11]:
# attributes in numpy
np1=np.array([[[1,2,4,4,5],[2,3,4,5,5],[3,4,5,6,7]]])
print(np1)
np1.ndim



[[[1 2 4 4 5]
  [2 3 4 5 5]
  [3 4 5 6 7]]]


3

In [25]:
#when there is different datatype
np3=np.array([1,2,3,44,'asj'])
print(np3)
np3.dtype

['1' '2' '3' '44' 'asj']


dtype('<U11')

In [26]:
#to crete the matrix we use the numpy array

my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(my_mat)
print(my_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
np4=np.array([[1,2,4,4,5],[2,3,4,5,5],[3,4,4,56,6],[33,3,3,3,3]])
np4.ndim

2