## Array creation 


## a) array(valuelist,dtype='float','int','boolean')

In [1]:
import numpy as np
np1=np.array([[1,2,4,4,5],[2,3,4,5,5]],dtype='int')
print(np1)
print(np1.shape)
print (np1.size)
print(np1.dtype)
print(np1.ndim)

np1[0:1,0:5:2]

[[1 2 4 4 5]
 [2 3 4 5 5]]
(2, 5)
10
int32
2


array([[1, 4, 5]])

## b) empty(shape,dtype,order)

In [8]:
np2=np.empty([3,3],dtype='int',order='C')

## c. zeros(shape,dtype,order)
> generate the numpy array with zeros of the given dimension 


In [11]:
np3=np.zeros([3,3],dtype='float',order= 'C')
print(np3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


TypeError: 'module' object does not support item assignment

## d. full(shape,fill_value,dtype)

In [14]:
np4=np.full([3,3],([3]),dtype='int')
print(np4)

np4[1:-1]

[[3 3 3]
 [3 3 3]
 [3 3 3]]


array([[3, 3, 3]])

In [35]:
#simple programe of the zeroes array
n = int(input())
import numpy as np
np_1=np.ones((n,n),dtype="int")
np_1[1:-1,1:-1]=0
print(np_1)

 6


[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


### e. numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)
- this will generate the numpay one dimensional array for given range of numbers 

In [17]:
np4=np.linspace(2,50,num=29)
print(np4)

[ 2.          3.71428571  5.42857143  7.14285714  8.85714286 10.57142857
 12.28571429 14.         15.71428571 17.42857143 19.14285714 20.85714286
 22.57142857 24.28571429 26.         27.71428571 29.42857143 31.14285714
 32.85714286 34.57142857 36.28571429 38.         39.71428571 41.42857143
 43.14285714 44.85714286 46.57142857 48.28571429 50.        ]


### f. tile(A,repetition)
> jo bhi array doge ussko repeat karke likh dega 


In [45]:
# it will return a array in repetition form
np6=np.array([2,3,4])
np7=np.tile(np6,3)
print(np7)
print(np6)

[2 3 4 2 3 4 2 3 4]
[2 3 4]


### g. Flatten the array
- issme jo bhi array rhta hai jis bhi dimension mai ho usse ye fun one dimension mai flat kar deta hai 


In [38]:
np6=np.array([[1,2,4,4],[3,6,4,5]])
np6.flatten('F')

array([1, 3, 2, 6, 4, 4, 4, 5])

### h. eye(N-rows,M-columns,k=diagonal as default 0)
- this will generate the identity matrix 


In [46]:
np.eye(10,10,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

### diagonal function


In [25]:
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

np.diag(mat)
res1=np.diag(mat,-1) # gives upper numbers 
np.diag(mat,-1) # gives lower numbers 
print(res1)

[4 8]


### reshape(shape)

In [60]:
np4=np.array([[3,4,5],[34,67,7]]).reshape(2,3)
print(np4)

[[ 3  4  5]
 [34 67  7]]


In [75]:
np5=np.arange(40)
print(np5)
np5.reshape(5,8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

### np.random .random()
### np.random .randint()

In [77]:
np.random.random()

0.9083079208950199

In [101]:
# to give the random number between given range 
np.random.randint(3,8)

6

In [120]:
np.reverse()

array([], shape=(0, 2), dtype=int32)