#                      Sorting
- sort
- argsort
- argmin
- argmax
- nanargmax
- nanargmin
- count_non_zero
- count_zero


In [3]:
import numpy as np

In [8]:
#-----------sorting---------------#
ar1=np.array([[7,4,2,6,5],[4,6,94,27,4]])
ar1.sort()
print(ar1)

#2 on axis 0
ar2=np.array([[7,4,2,6,5],[4,6,94,27,4]])
np.sort(ar1,axis=-1)
print(ar2)
#-----------argsort--------------#
mark=np.array([22,45,77,44,33,86])
name=np.array(['a','b','c','d','e','f'])
top2= name[np.argsort(mark)[::-1][:3]]
print(top2)



[[ 2  4  5  6  7]
 [ 4  4  6 27 94]]
[[ 7  4  2  6  5]
 [ 4  6 94 27  4]]
['f' 'c' 'b']


In [12]:
#2 on axis 0
ar1=np.array([[7,4,2,6,5],[4,6,94,27,4],[4,2,5,2,6]])
np.argmax(ar1)
print(ar1)

[[ 7  4  2  6  5]
 [ 4  6 94 27  4]
 [ 4  2  5  2  6]]


In [17]:
ar2=np.array([[2,4,3,1],[4,6,5,3]])
np.argmax(ar2,axis=1)

array([1, 1], dtype=int64)