# Arithematic Operations

In [17]:
#1 ------------------add ---------------------# 
import numpy as np
np1=np.arange(2,10)
np2=np.arange(3,11)
result=np1+np2
print(result)
#2
res=np.add(np1,np2)
print(res)

[ 5  7  9 11 13 15 17 19]
[ 5  7  9 11 13 15 17 19]


In [13]:
# ------------------substract---------------#
np1=np.arange(2,10)
np2=np.arange(3,11)
result=np1-np2
print(result)
#2
res=np.subtract(np1,np2)

[-1 -1 -1 -1 -1 -1 -1 -1]


In [14]:
# ------------------multiply---------------#
np1=np.arange(2,10)
np2=np.arange(3,11)
result=np1*np2
print(result)
#2
res=np.multiply(np1,np2)

[ 6 12 20 30 42 56 72 90]


In [32]:
# --------------------divide---------------#
np1=np.arange(2,10)
np2=np.arange(3,11)
res=np.divide(np1,np2)
print(res)

[0.66666667 0.75       0.8        0.83333333 0.85714286 0.875
 0.88888889 0.9       ]


In [19]:
#----------------floor division------------#
np1=np.arange(2,10)
np2=np.arange(3,11)
res=np.floor_divide(np2,np1)
print(res)

[1 1 1 1 1 1 1 1]


In [42]:
#------------reminder and mod------------------#
np1=np.arange(2,10)
np2=np.arange(1,9)
res=np.remainder(np1,np2)
print(res)
#2
res2=np.mod(np1,np2)
print(res2)

[0 1 1 1 1 1 1 1]
[0 1 1 1 1 1 1 1]


In [12]:

# ----------------sum of array---------------#
np1=np.arange(2,10)
np2=np.arange(3,11)
res=np.sum(np1)
print(res)
#2
np1.sum()

44


44

In [35]:
#---------------reciprocal----------------#
np1=np.array([0.2,3,4,6])
np2=np.arange(3,12)
res=np.reciprocal(np1)
print(res)


[5.         0.33333333 0.25       0.16666667]


In [41]:
#------------------power-------------------#
np1=np.arange(2,10)
np2=np.arange(3,11)
res=(np.power(np1,3)) * (np.power(np2,2))
print(res)


[   72   432  1600  4500 10584 21952 41472 72900]


In [43]:
#--------------cuberoot----------------#
np2=np.array([2,3,4,5,6,7,8])
np3=np.array([2,3,4,5,6,7,8])
np.cbrt(np2)

array([1.25992105, 1.44224957, 1.58740105, 1.70997595, 1.81712059,
       1.91293118, 2.        ])

In [20]:
#-------------reduce and accumulate_--------------------------#

a=np.array([1,2,3,4,5])
re=np.add.reduce(a)
print(re)
#or
np.sum(a)

#2 to get the moving sum of the array
re2=np.add.accumulate(a)
print(re2)
re3=np.multiply.accumulate(a)
print(re3)

15
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [ ]:
n = int(input())
def checkerboard(n):
    x=np.zeros((n,n),dtype='int')
    x[1::2,::2]=1
    x[::2,1::2]=1
    for i in range(n): 
        for j in range(n):  
            print(np.array(x[i][j]), end =" ")  
        print()
n=4
checkerboard(n)

#0r
n=int(input())
x=np.array([0,1],[1,0])
check=np.tile(x,n//2,n//2)
np.asarray()

 4


0 1 0 1 
1 0 1 0 
0 1 0 1 
1 0 1 0 


In [15]:
10/3
10//3
10%3
10*3
10**3
1000**(1/3)

9.999999999999998

In [13]:
1000**

3.9810717055349727