# Rounding Function

In [3]:
import numpy as np

In [4]:
#----------------around---------------#
np1=np.array([1.33,2.44444,3.62342,4.53433])
print(np1)

res=np.around(np1,2)
print(res)

[1.33    2.44444 3.62342 4.53433]
[1.33 2.44 3.62 4.53]


In [5]:
#------------------floor-------------#
np1=np.array([1.33,2.44444,3.62342,4.53433])
np.floor(np1)

array([1., 2., 3., 4.])

In [22]:
#---------------ceil---------------#
# one number greater than the given input number
np1=np.array([1.33,2.44444,3.62342,4.53433])
np.ceil(np1)

array([2., 3., 4., 5.])

In [48]:
#-------------------fix------------------#
np1=np.array([1.33,2.44444,3.62342,4.53433])
np.fix(np1)

array([1., 2., 3., 4.])

In [6]:
#-----------------rint-------------------#
np1=np.array([1.33,2.44444,3.62342,4.53433])
np.rint(np1)

array([1., 2., 4., 5.])

# Mathematics function 

In [29]:
#-----------negative------------------#
np2=np.array([2,3,4,5,6,7,8])
np3=np.array([2,3,4,5,6,7,8])
res=np.negative(np2)
print(res)

[-2 -3 -4 -5 -6 -7 -8]


In [8]:
#--------flat power-------------#
np2=np.array([2,3,4,5,6,7,8])
np3=np.array([3,4,4,5,6,7,8])
res=np.float_power(np2,np3)
np.array(res,dtype='int')


array([       8,       81,      256,     3125,    46656,   823543,
       16777216])

In [3]:
#--------------average-------------#
import numpy as np
np3=np.array([2,3,4,5])
res=np.average(np3,weights=[2,3,4,4])
print(res)

3.769230769230769
