# Transpose Operations
- transpose
- ndarray.T
- rollaxis
- swapaxes

In [1]:
import numpy as np


In [2]:
#-------------transpose-------------#
np1=np.arange(12).reshape(3,4)
print(np1)
np.transpose(np1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [8]:
#---------ndarray.T-----------#
np1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
np2=np.arange(2,12).reshape(2,5)
print(np2)
np.shape(np2)
aa=np.expand_dims(np2,axis=1)
np.shape(aa)
print(aa)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[[ 2  3  4  5  6]]

 [[ 7  8  9 10 11]]]
